version: 2
updates:
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "daily"
      time: "16:00"
      timezone: "US/Pacific"
    allow:
      - dependency-name: "content"
