
baseURL = '/'
languageCode = 'en-us'
title = "Lexical.cloud"
themesDir = 'themes'
theme = 'docsy'

# Language settings
contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

# You can add your own taxonomies
[taxonomies]
provider = "providers"
service = "services"
category = "categories"
feature = "features"
label = "labels"

[params]
copyright = "The Lexical.cloud Authors"
#privacy_policy = "https://policies.google.com/privacy"

# Repository configuration (URLs for in-page links to opening issues and suggesting changes)
github_repo = "https://github.com/lexical-cloud/lexical-cloud-hugo"
# An optional link to a related project repo. For example, the sibling repository where your product code lives.
#github_project_repo = "https://github.com/lexical-cloud/lexical-cloud.github.io"

[params.taxonomy]
# set taxonomyCloud = [] to hide taxonomy clouds
taxonomyCloud = ["providers", "services", "categories", "features", "labels"]

# If used, must have same length as taxonomyCloud
taxonomyCloudTitle = ["Providers", "Services", "Categories", "Features", "Labels"]

# set taxonomyPageHeader = [] to hide taxonomies on the page headers
taxonomyPageHeader = ["providers", "services", "categories", "features", "labels"]

# User interface configuration
[params.ui]
#  Set to true to disable breadcrumb navigation.
breadcrumb_disable = false
# Set to true to disable the About link in the site footer
footer_about_disable = false
# Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top navbar
navbar_logo = true
# Set to true if you don't want the top navbar to be translucent when over a `block/cover`, like on the homepage.
navbar_translucent_over_cover_disable = false
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = false
# Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
sidebar_search_disable = false
