name: ack fork pr 
concurrency: staging
on:
  pull_request_target:
    branches:
      - 'main'

permissions:
  pull-requests: write

jobs:

  comment-on-pr:
    # this workflow should only run on forks targeting the original repo
    if: |
      github.repository == 'lexical-cloud/lexical-cloud-docs-hugo' &&
      github.event.pull_request.head.repo.fork == true
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/github-script@v6
        env:
          PR_NUM: ${{ github.event.pull_request.number }}
          RUN_NUM: ${{ github.run_number }}
        with:
          script: |
            const { PR_NUM, RUN_NUM } = process.env
            github.rest.issues.createComment({
              issue_number: PR_NUM,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `
            ### Changes in this forked PR (run ${RUN_NUM}) require approval.

            @lexical-cloud/admins will perform the following actions:
              - [ ] Review the proposed changes.
              - [ ] Decide whether to proceed with the build.
              - [ ] If accepting, approve and monitor the build run.

            Expect a response on this comment when actions are completed.`
            })
