name: approve fork pr
concurrency: staging
on:
  pull_request_review:
    types:
      - submitted

defaults:
  run:
    shell: bash

jobs:

  preconditions:
    if: |
       github.event.pull_request.head.repo.fork == true &&
       github.event_name == 'pull_request_review' &&
       github.event.review.state == 'approved' &&
       github.actor == 'wahlax-llc'
    runs-on: ubuntu-22.04
    steps:
      - name: Precondition passed output
        run: |
          echo "Preconditions passed"

  save-pr-data:
    needs: preconditions
    uses: ./github/workflows/pr-data-to-artifact.yml
    with:
      pr-number: ${{ github.event.pull_request.number }}

  build-and-deploy:
    needs: save-pr-data
    uses: ./.github/workflows/hugo-build.yml
    with:
      is-deployable: ${{  github.event.pull_request.head.repo.fork == false  }}
      branch-name: ${{ github.head_ref }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
