name: dependabot pr
on:
  pull_request:
    types:
      - opened

permissions:
  pull-requests: write

jobs:
  approve-pr:
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-22.04
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Approve a PR
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
