name: deploy gh pages
concurrency: staging
on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

defaults:
  run:
    shell: bash

jobs:

  preconditions:
    runs-on: ubuntu-22.04
    outputs:
      base-url: ${{ steps.build-setup.base-url }}
    steps:
      - name: Build setup
        id: build-setup
        run: |
          echo "base-url=/${GITHUB_REPOSITORY#*/}/" >> ${GITHUB_OUTPUT}


  build:
    needs: preconditions
    uses: ./.github/workflows/hugo-build.yml
    with:
      is-deployable: true
      artifact-name: gh-pages
      branch-name: ${{ github.head_ref }}
      base-url: ${{ needs.preconditions.base-url }} 
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    needs: deploy-prep
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
