name: finalize pr
concurrency: staging
on:
  workflow_run:
    workflows:
      - 'validate pr'
    types:
      - completed

defaults:
  run:
    shell: bash

jobs:

  build:
    if: |
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'
    needs: preconditions
    runs-on: ubuntu-22.04
    environment: staging
    steps:

      - name: Checkout project with submodules
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/download-artifact@v3
        with:
          name: github-pages

      - name: list files
        run: |
          echo "PR is ${PR_NUM}"
          echo "RUN is ${RUN_NUM}"
          ls
          git status
          exit 1
