name: merge pr
concurrency: staging
on:
  pull_request:
    branches:
      - 'main'
    types:
      - closed

permissions:
  pull-requests: write

jobs:
  if_merged:
    # this workflow should not run on forks
    if: |
      github.repository == 'lexical-cloud/lexical-cloud-docs-hugo' &&
      github.event.pull_request.merged == true
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout project with submodules
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout branch for pr on public submodule 
        id: checkout-public-pr-branch
        run: |
          cd public
          echo "head-commit-sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT          
          git checkout deploy/hugo-pr-$PR_NUM
          echo "branch-commit-sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT          
        continue-on-error: true
        env:
          PR_NUM: ${{ github.event.pull_request.number }}
          PR_URL: ${{ github.event.pull_request.html_url }}

      - name: Reminder to complete pr to lexical-cloud.github.io
        if: |
          steps.checkout-public-pr-branch.outputs.branch-commit-sha != '' &&
          steps.checkout-public-pr-branch.outputs.head-commit-sha != steps.checkout-public-pr-branch.outputs.branch-commit-sha
        run: exit 1
