name: merge pr
on:
  pull_request:
    branches:
      - 'main'
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout project with submodules
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true
          token: ${{ secrets.LC_GP_CI }}

      - name: Create PR for public submodule
        run: |
          cd public
          git checkout deploy/hugo-pr-$PR_NUM
          gh pr create --title "Static site from pr $PR_NUM on lexical-cloud-docs-hugo" --body "See $PR_URL"
        env:
          PR_NUM: ${{ github.event.pull_request.number }}
          PR_URL: ${{ github.event.pull_request.html_url }}
          PR_COMMIT: ${{ github.event.pull_request.head.sha }}
