name: pr data to artifact

on:
  workflow_call:
    inputs:
      pr-number:
        required: true
        type: number
      
defaults:
  run:
    shell: bash

jobs:

  save-artifact:
    runs-on: ubuntu-22.04
    steps:

      - name: Send artifact to data
        run: |
          echo "${{ inputs.pr-number }}" > pr-data.txt

      - name: Upload pr data to artifact
        uses: actions/upload-artifact@v3
        with:
          name: pr-data
          path: pr-data.txt
