name: validate pr
on: pull_request

jobs:
  validate:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0         # Fetch all history for .GitInfo and .Lastmod
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.89.4'
          extended: true

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '14.17.5'
          cache: 'npm'
          #cache-dependency-path: 'themes/docsy/package-lock.json'

      - run: npm ci
      - run: hugo --minify
