name: validate fork pr
concurrency: staging
on:
  pull_request_target:
    branches:
      - 'main'

defaults:
  run:
    shell: bash

jobs:
  preconditions:
    if: |
       startsWith(github.head_ref,'dependabot/submodules/public-') == false &&
       github.event.pull_request.head.repo.fork == true
    runs-on: ubuntu-22.04
    environment: staging
    steps:
      - name: Precondition passed output
        run: |
          echo "Preconditions passed"
   
  build:
    needs: preconditions
    runs-on: ubuntu-22.04
    environment: staging
    outputs:
      static-site-sha: ${{ steps.save-static-site.outputs.commit-sha }}
    steps:
      - name: Checkout project with submodules
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.89.4'
          extended: true

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '14.17.5'
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
            themes/docsy/package-lock.json

      - name: Install project dependencies
        run: |
          npm ci

      - name: Install docsy dependencies
        run: |
          cd themes/docsy
          npm ci

      - name: Generate static site with hugo
        run: |
          hugo --minify
